### ISSUE TITLE
Setting splitter position to PolymerTemplate does nothing

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-split-layout-flow#72]
Vaadin 14.0.8

I'm referencing a SplitLayout from PolymerTemplate via

```java
@Route("")
@Tag("my-template")
@JsModule("./src/my-template.js")
@PWA(name = "Project Base for Vaadin", shortName = "Project Base")
public class MainView extends PolymerTemplate<TemplateModel> {

    @Id
    private SplitLayout splitLayout;

    public MainView() {
        splitLayout.setSplitterPosition(0.1);
    }
}
```

however the splitter position is kept at the default 50%.

**Comment by mvysny** [comment]
[skeleton-starter-flow.zip](https://github.com/vaadin/vaadin-split-layout-flow/files/3712097/skeleton-starter-flow.zip)

Example app which demonstrates the issue.

**Comment by alvarezguille** [comment]
Thanks for reporting and for the simple example.
The issue is related to the current implementation that depends on references to components added to the layout, those references do not exist if the layout children are initialized in a template.
It should be possible to use js api to do the same changes when those references are not available, I'll continue with this tomorrow.
